apiVersion: apps/v1
kind: Deployment
metadata:
  name: fun-ibw-deployment
  labels:
    app: fun-ibw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ibw
  template:
    metadata:
      labels:
        app: fun-ibw
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 11000
        runAsGroup: 11000
        fsGroup: 11000
      containers:
      - name: fun-ibw
        image: quay.io/onzack/ibwdailyfun:1.0.0
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fun-ibw-svc
  labels:
    app: fun-ibw
spec:
  type: ClusterIP
  ports:
  - port: 9090
    name: http
  selector:
    app: fun-ibw
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fun-ibw-ingress
spec:
  rules:
  - host: 127.0.0.1.fun-ibw.sslip.io
    http:
      paths:
      - path: /fun
        pathType: Prefix
        backend:
          service:
            name: fun-ibw-svc
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fun-ibw
spec:
  podSelector:
    matchLabels:
      app: fun-ibw
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            app.kubernetes.io/instance: traefik-kube-system
            app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8080
