---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fun-ibw-netpol
spec:
  podSelector:
    matchLabels:
      app: fun-ibw
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            app.kubernetes.io/instance: rke2-ingress-nginx
            app.kubernetes.io/name: rke2-ingress-nginx
      ports:
        - protocol: TCP
          port: 8090
  egress: []