---
apiVersion: v1
kind: Service
metadata:
  name: fun-ibw-svc
  labels:
    app: fun-ibw
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fun-ibw-deployment